disabled_rules: # rule identifiers to exclude from running
  - nesting
  - todo
  - line_length

identifier_name:
  excluded:
    - r
    - id
    - ok

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Tests
